api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apyKey:
                name: Authorization
                type: header
    title: API platform with symfony 5
    version: 1.0
    show_webby: false